#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE   2
#define TRANSITION_TIME             0.5

#define PIPE_SPAWN_FREQUENCY        0.003
#define UPPER_SCREEN_PIPE_THRESHOLD 0.7
#define LOWER_SCREEN_PIPE_THRESHOLD 0.3
#define PIPE_MOVEMENT_SPEED         0.01

#define DOLLAR_SPAWN_FREQUENCY      0.004
#define DOLLAR_MOVEMENT_SPEED       0.01

#define BIRD_COLLISION_BITMASK      0x000001
#define OBSTACLE_COLLISION_BITMASK  0x000002
#define POINT_COLLISION_BITMASK     0x000003
#define DOLLAR_COLLISION_BITMASK    0x000004

#define BIRD_FLYING_SPEED           0.00375
#define BIRD_FALLING_SPEED          0.0025
#define BIRD_FLY_DURATION           0.25

#define POINT_PASS_SCORE            100
#define DOLLAR_SCORE                200

#endif // __DEFINITIONS_H__
